// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHw-jOjxA-L_O2n-miPXDkOm5efyjwmD4',
    appId: '1:1007199571452:web:621a586209d4d37fef7679',
    messagingSenderId: '1007199571452',
    projectId: 'guardian-64640',
    authDomain: 'guardian-64640.firebaseapp.com',
    storageBucket: 'guardian-64640.firebasestorage.app',
    measurementId: 'G-WYZB9LF7Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPx-kzvA0mP2F5VdrPHsvuiMAWRTtQKf4',
    appId: '1:1007199571452:android:4c51825e5413c1a7ef7679',
    messagingSenderId: '1007199571452',
    projectId: 'guardian-64640',
    storageBucket: 'guardian-64640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBshWYieagP_ZDGTuaXsnQOCBcORTwpOXQ',
    appId: '1:1007199571452:ios:05f64ef1c839f2f7ef7679',
    messagingSenderId: '1007199571452',
    projectId: 'guardian-64640',
    storageBucket: 'guardian-64640.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBshWYieagP_ZDGTuaXsnQOCBcORTwpOXQ',
    appId: '1:1007199571452:ios:05f64ef1c839f2f7ef7679',
    messagingSenderId: '1007199571452',
    projectId: 'guardian-64640',
    storageBucket: 'guardian-64640.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHw-jOjxA-L_O2n-miPXDkOm5efyjwmD4',
    appId: '1:1007199571452:web:91131ba170a35f53ef7679',
    messagingSenderId: '1007199571452',
    projectId: 'guardian-64640',
    authDomain: 'guardian-64640.firebaseapp.com',
    storageBucket: 'guardian-64640.firebasestorage.app',
    measurementId: 'G-53BDBWEK72',
  );

}